version: "3.8"

services:
  web:
    build: .
    container_name: vulnerable-auth-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
