version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///broken_auth.db
      - SECRET_KEY=your-super-secret-key
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0"
